CREATE TABLE IF NOT EXISTS biz_material (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    title VARCHAR(200) NOT NULL COMMENT '材料标题',
    original_filename VARCHAR(255) NOT NULL COMMENT '原始文件名快照',
    file_id BIGINT NOT NULL COMMENT '关联 sys_file 文件记录 ID',
    file_type VARCHAR(50) NULL COMMENT '文件类型，如 pdf、docx、txt',
    file_size BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小，单位字节',
    file_md5 VARCHAR(32) NULL COMMENT '文件 MD5 快照',
    storage_path VARCHAR(500) NOT NULL COMMENT '文件存储路径快照',
    status VARCHAR(32) NOT NULL DEFAULT 'processing' COMMENT '材料状态：processing、available、failed',
    segment_count INT NOT NULL DEFAULT 0 COMMENT '当前可用片段数量',
    last_process_time DATETIME NULL COMMENT '最近处理完成时间',
    error_message TEXT NULL COMMENT '最近一次处理失败原因',
    remark VARCHAR(500) NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_material_user_id (user_id),
    KEY idx_biz_material_file_id (file_id),
    KEY idx_biz_material_status (status),
    KEY idx_biz_material_create_time (create_time),
    KEY idx_biz_material_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='材料主表';

CREATE TABLE IF NOT EXISTS biz_material_process_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    material_id BIGINT NOT NULL COMMENT '材料 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    file_id BIGINT NOT NULL COMMENT '本次处理对应的 sys_file 文件记录 ID',
    file_md5 VARCHAR(32) NULL COMMENT '本次处理文件 MD5 快照',
    original_filename VARCHAR(255) NOT NULL COMMENT '本次处理原始文件名快照',
    process_type VARCHAR(32) NOT NULL COMMENT '处理类型：initial、reprocess',
    status VARCHAR(32) NOT NULL DEFAULT 'processing' COMMENT '处理状态：processing、success、failed',
    deleted_count INT NOT NULL DEFAULT 0 COMMENT '覆盖处理时删除的旧片段数量',
    segment_count INT NOT NULL DEFAULT 0 COMMENT '本次新写入片段数量',
    error_message TEXT NULL COMMENT '失败原因',
    started_at DATETIME NULL COMMENT '处理开始时间',
    finished_at DATETIME NULL COMMENT '处理结束时间',
    duration_ms BIGINT NULL COMMENT '处理耗时，单位毫秒',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_mpr_material_id (material_id),
    KEY idx_biz_mpr_user_id (user_id),
    KEY idx_biz_mpr_file_id (file_id),
    KEY idx_biz_mpr_status (status),
    KEY idx_biz_mpr_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='材料处理记录表';

CREATE TABLE IF NOT EXISTS biz_qa_session (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    title VARCHAR(200) NOT NULL COMMENT '会话标题',
    status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '会话状态：active、archived',
    last_message_time DATETIME NULL COMMENT '最后消息时间',
    message_count INT NOT NULL DEFAULT 0 COMMENT '消息数量',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_qa_session_user_id (user_id),
    KEY idx_biz_qa_session_status (status),
    KEY idx_biz_qa_session_update_time (update_time),
    KEY idx_biz_qa_session_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='问答会话表';

CREATE TABLE IF NOT EXISTS biz_qa_message (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    session_id BIGINT NOT NULL COMMENT '问答会话 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    role VARCHAR(32) NOT NULL COMMENT '消息角色：user、assistant、system',
    content LONGTEXT NOT NULL COMMENT '消息正文',
    source_segments_json TEXT NULL COMMENT '来源片段快照 JSON 字符串',
    model_name VARCHAR(100) NULL COMMENT '模型名称',
    ai_call_log_id BIGINT NULL COMMENT '关联 AI 调用日志 ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_qa_message_session_id (session_id),
    KEY idx_biz_qa_message_user_id (user_id),
    KEY idx_biz_qa_message_role (role),
    KEY idx_biz_qa_message_ai_call_log_id (ai_call_log_id),
    KEY idx_biz_qa_message_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='问答消息表';

CREATE TABLE IF NOT EXISTS biz_qa_session_material (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    session_id BIGINT NOT NULL COMMENT '问答会话 ID',
    material_id BIGINT NOT NULL COMMENT '材料 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_qsm_session_material (session_id, material_id, deleted),
    KEY idx_biz_qsm_material_id (material_id),
    KEY idx_biz_qsm_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='问答会话材料关联表';

CREATE TABLE IF NOT EXISTS biz_writing_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    title VARCHAR(200) NOT NULL COMMENT '任务标题',
    writing_type VARCHAR(32) NOT NULL COMMENT '写作类型：outline、draft、polished、title',
    topic VARCHAR(500) NOT NULL COMMENT '写作主题',
    requirement TEXT NULL COMMENT '写作要求',
    input_content LONGTEXT NULL COMMENT '润色类任务的原始内容',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '任务状态：pending、running、success、failed',
    error_message TEXT NULL COMMENT '失败原因',
    started_at DATETIME NULL COMMENT '任务开始时间',
    finished_at DATETIME NULL COMMENT '任务结束时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_writing_task_user_id (user_id),
    KEY idx_biz_writing_task_type (writing_type),
    KEY idx_biz_writing_task_status (status),
    KEY idx_biz_writing_task_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='写作任务表';

CREATE TABLE IF NOT EXISTS biz_writing_task_material (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    task_id BIGINT NOT NULL COMMENT '写作任务 ID',
    material_id BIGINT NOT NULL COMMENT '材料 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_wtm_task_material (task_id, material_id, deleted),
    KEY idx_biz_wtm_material_id (material_id),
    KEY idx_biz_wtm_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='写作任务材料关联表';

CREATE TABLE IF NOT EXISTS biz_writing_result (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    task_id BIGINT NOT NULL COMMENT '写作任务 ID',
    user_id BIGINT NOT NULL COMMENT '所属用户 ID',
    version_no INT NOT NULL COMMENT '结果版本号',
    content LONGTEXT NOT NULL COMMENT '生成内容',
    source_segments_json TEXT NULL COMMENT '来源片段快照 JSON 字符串',
    model_name VARCHAR(100) NULL COMMENT '模型名称',
    ai_call_log_id BIGINT NULL COMMENT '关联 AI 调用日志 ID',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_wr_task_id (task_id),
    KEY idx_biz_wr_user_id (user_id),
    KEY idx_biz_wr_task_version (task_id, version_no, deleted),
    KEY idx_biz_wr_ai_call_log_id (ai_call_log_id),
    KEY idx_biz_wr_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='写作结果表';

CREATE TABLE IF NOT EXISTS biz_ai_call_log (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    user_id BIGINT NOT NULL COMMENT '调用用户 ID',
    business_type VARCHAR(50) NOT NULL COMMENT '业务类型：material_process、material_vector_delete、writing、qa',
    business_id BIGINT NULL COMMENT '业务 ID，如材料 ID、任务 ID 或会话 ID',
    endpoint VARCHAR(255) NOT NULL COMMENT 'Python 服务接口路径',
    model_name VARCHAR(100) NULL COMMENT '模型名称',
    material_ids_json TEXT NULL COMMENT '本次调用涉及的材料 ID 快照 JSON 字符串',
    request_summary TEXT NULL COMMENT '请求摘要，不保存完整请求体',
    response_summary TEXT NULL COMMENT '响应摘要，不保存完整响应体',
    status VARCHAR(32) NOT NULL COMMENT '调用状态：success、failed',
    http_status INT NULL COMMENT 'Python HTTP 状态码',
    error_code VARCHAR(100) NULL COMMENT 'Python 错误码',
    error_message TEXT NULL COMMENT '错误信息',
    source_count INT NOT NULL DEFAULT 0 COMMENT '来源片段数量',
    trace_id VARCHAR(100) NULL COMMENT '调用链追踪 ID',
    duration_ms BIGINT NULL COMMENT '调用耗时，单位毫秒',
    started_at DATETIME NULL COMMENT '调用开始时间',
    finished_at DATETIME NULL COMMENT '调用结束时间',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    create_by BIGINT NULL COMMENT '创建人 ID',
    update_by BIGINT NULL COMMENT '更新人 ID',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0=正常，1=已删除',
    PRIMARY KEY (id),
    KEY idx_biz_ai_call_user_id (user_id),
    KEY idx_biz_ai_call_business (business_type, business_id),
    KEY idx_biz_ai_call_status (status),
    KEY idx_biz_ai_call_http_status (http_status),
    KEY idx_biz_ai_call_trace_id (trace_id),
    KEY idx_biz_ai_call_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 调用日志表';
